trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureServiceConnection: 'Azure-DevOps-Service-Connection'
  resourceGroup: 'rg-epicbook-tfstate'
  storageAccount: '<YOUR_STORAGE_ACCOUNT_NAME>'
  containerName: 'tfstate'
  tfstateKey: 'epicbook.terraform.tfstate'

steps:
- task: AzureCLI@2
  displayName: 'Terraform Init & Apply'
  inputs:
    azureSubscription: '$(azureServiceConnection)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      terraform init \
        -backend-config="resource_group_name=$(resourceGroup)" \
        -backend-config="storage_account_name=$(storageAccount)" \
        -backend-config="container_name=$(containerName)" \
        -backend-config="key=$(tfstateKey)"
      
      terraform plan -var="db_admin_password=$(DB_PASSWORD)" -var="ssh_public_key=$(SSH_PUB_KEY)" -out=tfplan
      terraform apply -auto-approve tfplan
